[package]
name = "moonlink_table_metadata"
version = { workspace = true }
edition = { workspace = true }
license = "MIT"

[dependencies]
bincode = { workspace = true }
more-asserts = { workspace = true }
serde = { workspace = true }
