apiVersion: v1
kind: Service
metadata:
  name: moonlink-service
spec:
  type: LoadBalancer
  # IP assigned by kubernetes automatically.
  selector:
    app: moonlink-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
