[workspace]
members = [
    "src/moonlink",
    "src/moonlink_connectors",
    "src/moonlink_backend",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
async-trait = "0.1"

tokio-postgres = { git = "ssh://git@github.com/Mooncake-labs/rust-postgres.git"}
arrow = "54.2.1"
thiserror = "2.0.12"
parquet = "54.2.1"
tempfile = "3.18.0"
futures = "0.3.31"
multimap = "0.10.0"
chrono = "0.4.40"
num-traits = "0.2.19"
postgres-replication = { git = "ssh://git@github.com/Mooncake-labs/rust-postgres.git" }
pg_escape = "0.1.1"
pin-project-lite = "0.2"
tracing = { version = "0.1", default-features = true }
bigdecimal = { version = "0.4.6", features = ["std"] }
uuid = { version = "1.10.0", features = ["v4"] }
serde_json = { version = "1.0", features = ["std"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros"] }
bytes = "1.0"
byteorder = "1.5.0"
