[workspace]
members = ["src/moonlink", "src/moonlink_backend", "src/moonlink_connectors"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
arrow = { version = "54", default-features = false }
arrow-array = "54"
arrow-schema = "54"
async-trait = "0.1"
bincode = "2"
bitstream-io = "4"
chrono = { version = "0.4", default-features = false }
crc32fast = "1"
futures = { version = "0.3", default-features = false }
iceberg = { git = "https://github.com/apache/iceberg-rust.git", rev = "513376cb04b899edf457918c3852a786a292071c", default-features = false, features = [
  "storage-s3",
  "storage-fs",
] }
multimap = { version = "0.10", default-features = false }
num-traits = "0.2"
opendal = { version = "0.53", default-features = false, features = [
  "services-s3",
] }
parquet = { version = "54", default-features = false, features = ["arrow"] }
postgres-replication = { git = "https://github.com/Mooncake-labs/rust-postgres.git" }
roaring = "0.10"
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1.38", default-features = false, features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
tokio-postgres = { git = "https://github.com/Mooncake-labs/rust-postgres.git" }
url = "2.5"
uuid = { version = "1.16", default-features = false, features = ["v4"] }

[profile.release-with-debug]
inherits = "release"
debug = true
