[workspace]
members = ["src/moonlink", "src/moonlink_backend", "src/moonlink_connectors"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
async-trait = "0.1"
bincode = "2"

tokio-postgres = { git = "ssh://git@github.com/Mooncake-labs/rust-postgres.git" }
arrow = "54.2"
thiserror = "2.0"
parquet = "54.2"
tempfile = "3.18"
futures = "0.3"
multimap = "0.10"
chrono = "=0.4.39"
num-traits = "0.2"
postgres-replication = { git = "ssh://git@github.com/Mooncake-labs/rust-postgres.git" }
tokio = { version = "1.38", default-features = false, features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
uuid = { version = "1.16", default-features = false, features = ["v4"] }
arrow-array = "54.2"
arrow-schema = "54.2"
serde_json = { version = "1.0", default-features = false, features = ["std"] }
iceberg = { git = "https://github.com/apache/iceberg-rust.git", rev = "b4bc6dd15ae4f7a4b1c9ce555e3458089a83e228", default-features = false, features = [
  "storage-s3",
  "storage-fs",
] }
url = "2.5"
roaring = { version = "0.10", git = "https://github.com/RoaringBitmap/roaring-rs.git" }
crc32fast = "1.3"
opendal = { version = "0.53", default-features = false, features = [
  "services-s3",
] }
bitstream-io = "3.2"

[profile.release-with-debug]
inherits = "release"
debug = true
