[graph]
all-features = true

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Zlib",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "CDLA-Permissive-2.0",
    # Moonlink permission.
    "LicenseRef-BSL-1.1",
]

[sources]
allow-git = [
    "https://github.com/apache/iceberg-rust.git",
    "https://github.com/Mooncake-labs/rust-postgres.git",
]

# TODO(hjiang): Cleanup these unmaintained crates.
[advisories]
ignore = [
    "RUSTSEC-2024-0436", # paste - unmaintained
]

# TODO(hjiang): Resolve all duplicate dependencies.
[bans]
skip = [
    { name = "base64" },
    { name = "core-foundation" },
    { name = "crypto-bigint" },
    { name = "getrandom" },
    { name = "hashbrown" },
    { name = "h2" },
    { name = "http" },
    { name = "http-body" },
    { name = "hyper" },
    { name = "hyper-rustls" },
    { name = "itertools" },
    { name = "ordered-float" },
    { name = "rand" },
    { name = "rand_chacha" },
    { name = "rand_core" },
    { name = "regex-automata" },
    { name = "regex-syntax" },
    { name = "rustls" },
    { name = "rustls-native-certs" },
    { name = "rustls-pemfile" },
    { name = "rustls-webpki" },
    { name = "security-framework" },
    { name = "thiserror" },
    { name = "thiserror-impl" },
    { name = "tokio-rustls" },
    { name = "twox-hash" },
    { name = "typed-builder" },
    { name = "typed-builder-macro" },
    { name = "wasi" },
    { name = "webpki-roots" },
    { name = "windows_aarch64_gnullvm" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_gnullvm" },
    { name = "windows_i686_msvc" },
    { name = "windows-strings" },
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_gnullvm" },
    { name = "windows_x86_64_msvc" },
]
