[graph]
all-features = true

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Zlib",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "CDLA-Permissive-2.0",
    # Moonlink permission.
    "LicenseRef-BSL-1.1",
]

[sources]
allow-git = [
    "https://github.com/apache/iceberg-rust.git",
    "https://github.com/Mooncake-labs/rust-postgres.git",
]

# TODO(hjiang): Cleanup these unmaintained crates.
[advisories]
ignore = [
    "RUSTSEC-2024-0436", # paste - unmaintained
]

# TODO(hjiang): Resolve all duplicate dependencies.
[bans]
skip = [
    { name = "getrandom" },
    { name = "hashbrown" },
    { name = "itertools" },
    { name = "ordered-float" },
    { name = "rand" },
    { name = "rand_chacha" },
    { name = "rand_core" },
    { name = "regex-automata" },
    { name = "regex-syntax" },
    { name = "thiserror" },
    { name = "thiserror-impl" },
    { name = "typed-builder" },
    { name = "typed-builder-macro" },
    { name = "wasi" },
    { name = "windows-sys" },
]
