apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonlink-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonlink-dev
  template:
    metadata:
      labels:
        app: moonlink-dev
    spec:
      containers:
      - name: moonlink-dev
        image: moonlink:dev
        env:
        - name: PGHOST
          value: localhost
        - name: PGUSER
          value: user
        - name: PGPASSWORD
          value: password
        - name: PGDATABASE
          value: mydb
        - name: PGPORT
          value: "5432"
        volumeMounts:
        - name: shared-cache-directory
          mountPath: /tmp/moonlink

      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        # nginx serves local files under certain directory.
        - name: shared-cache-directory
          mountPath: /usr/share/nginx/html

      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_INITDB_ARGS
          value: "-c wal_level=logical"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: pgdata
        emptyDir: {}
      # Shared cache directory between data server and moonlink.
      - name: shared-cache-directory
        emptyDir: {}
