[package]
name = "moonlink_backend"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
arrow-array.workspace = true
moonlink = { path = "../moonlink", features = ["test-utils"] }
moonlink_connectors = { path = "../moonlink_connectors" }
parquet = { workspace = true, features = ["arrow"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
serial_test = "3.0"
tempfile = { workspace = true }
tokio-postgres = { workspace = true }
