[package]
name = "moonlink"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
tokio.workspace = true
arrow.workspace = true
thiserror.workspace = true
parquet.workspace = true
uuid.workspace = true
futures.workspace = true
multimap.workspace = true
[dev-dependencies]
tempfile.workspace = true
