services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/rust:latest
    volumes:
      - ..:/workspaces/pg_moonlink:cached
    network_mode: host
    command: sleep infinity

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    command: ["-c", "wal_level=logical"]
    network_mode: host

  iceberg:
    image: tabulario/iceberg-rest:latest
    ports:
      - "8181:8181"
    network_mode: host
