services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/moonlink:cached
    networks:
      - shared_network
    depends_on:
      - minio
      - postgres
    command: sleep infinity

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - shared_network
    command: ["-c", "wal_level=logical"]

  minio:
    image: minio/minio:latest
    hostname: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      shared_network:
        aliases:
          - s3.local
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI

volumes:
  minio-data:

networks:
  shared_network:
    driver: bridge
