apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonlink-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonlink-deployment
  template:
    metadata:
      labels:
        app: moonlink-deployment
    spec:
      containers:
      # Moonlink deployment, which serves REST API and TCP rpc requests.
      - name: moonlink-deployment
        image: us-west1-docker.pkg.dev/coral-ring-465417-r0/moonlink-standalone-experiment/moonlink-deployment:8aa98bda-70da-47ab-abcf-0eadda072665
        command: ["/app/moonlink_service"]
        args:
        - "/tmp/moonlink"
        - "--no-rest-api"
        - "--tcp-port=3031"
        env:
        # TODO(hjiang): Remove all pg test related envs before release. 
        - name: PGHOST
          value: localhost
        - name: PGUSER
          value: user
        - name: PGPASSWORD
          value: password
        - name: PGDATABASE
          value: mydb
        - name: PGPORT
          value: "5432"
        volumeMounts:
        - name: shared-cache-directory
          mountPath: /tmp/moonlink
        ports:
        # Port number for REST API server.
        - containerPort: 3030
        # Port number for TCP rpc server.
        - containerPort: 3031

      # Data server, which serves data plane requests.
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        # nginx serves local files under certain directory.
        - name: shared-cache-directory
          mountPath: /usr/share/nginx/html

      # TODO(hjiang): Currently serves merely as source database to sync from, need to remove before release.
      - name: postgres
        image: postgres:17
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_INITDB_ARGS
          value: "-c wal_level=logical"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: pgdata
        emptyDir: {}
      # Shared cache directory between data server and moonlink.
      - name: shared-cache-directory
        emptyDir: {}
