# to deploy: DATA_SERVER_URI=http://myserver:8080 envsubst < deploy/aws/dev/deployment/moonlink_deployment.yaml | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonlink-deployment-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonlink-deployment-dev
  template:
    metadata:
      labels:
        app: moonlink-deployment-dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      # Moonlink deployment, which serves REST API and TCP rpc requests.
      - name: moonlink-deployment-dev
        image: docker.io/lohpaul9/moonlink:latest
        command: ["/app/moonlink_service"]
        args:
        - "/tmp/moonlink"
        - "--no-rest-api"
        - "--tcp-port=3031"
        - "--data-server-uri=$(DATA_SERVER_URI)"
        env:
        - name: DATA_SERVER_URI
          value: "${DATA_SERVER_URI}"
        volumeMounts:
        - name: shared-cache-directory
          mountPath: /tmp/moonlink
        ports:
        # Port number for REST API server.
        - containerPort: 3030
        # Port number for TCP rpc server.
        - containerPort: 3031
        # Port number for readiness probe.
        - containerPort: 5050 
        readinessProbe:
          httpGet:
            path: /ready
            port: 5050
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3

      # Data server, which serves data plane requests.
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        # nginx serves local files under certain directory.
        - name: shared-cache-directory
          mountPath: /usr/share/nginx/html

      # Act as remote postgres instance.
      - name: postgres
        image: mooncakelabs/pg_mooncake
        env:
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: pgdata
        emptyDir: {}
      # Shared cache directory between data server and moonlink.
      - name: shared-cache-directory
        emptyDir: {}
