[package]
name = "moonlink_error"
version = { workspace = true }
edition = { workspace = true }
license = "MIT"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
regex = { workspace = true }
