[package]
name = "moonlink_service"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
arrow-ipc = { workspace = true }
arrow-schema = { workspace = true }
clap = { workspace = true }
moonlink = { path = "../moonlink" }
moonlink_backend = { path = "../moonlink_backend" }
moonlink_metadata_store = { path = "../moonlink_metadata_store" }
moonlink_rpc = { path = "../moonlink_rpc" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
