[package]
name = "moonlink_service"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
clap = { workspace = true }
moonlink_backend = { path = "../moonlink_backend" }
moonlink_metadata_store = { path = "../moonlink_metadata_store" }
moonlink_rpc = { path = "../moonlink_rpc" }
thiserror = { workspace = true }
tokio = { workspace = true }
