[package]
name = "moonlink_proto"
version = { workspace = true }
edition = { workspace = true }
license = "MIT"

[dependencies]
bytes = { workspace = true }
prost = { workspace = true }

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"
